[project]
name = "wallet-library"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pycouchdb>=1.16.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.3",
]
